edit_uri: edit/master/docs/ReadTheDocs
site_author: Zachary Loeber
copyright: PSModuleBuild is licensed under the <a href='https://github.com/zloeber/PSModuleBuild/master/LICENSE.md'> license
theme: readthedocs
site_name: PSModuleBuild Docs
Pages:
  Home: Home\index.md
  Introduction: Introduction\Introduction.md
  Usage:
  - 1 - Initialization: Usage\1 - Initialization.md
  - 2 - Make Your Module: Usage\2 - Make Your Module.md
  - 3 - Build A Release: Usage\3 - Build A Release.md
  - 4 - Test A Release: Usage\4 - Test A Release.md
  - 5 - Publish A Release: Usage\5 - Publish A Release.md
  - 6 - Your Next Release: Usage\6 - Your Next Release.md
  - 7 - Maintaining Documentation: Usage\7 - Maintaining Documentation.md
  - 8 - Special Files: Usage\8 - Special Files.md
  - 9 - PSModuleBuild Configuration: Usage\9 - PSModuleBuild Configuration.md
repo_url: https://github.com/zloeber/PSModuleBuild
